# .github/workflows/main.yml

# この自動化プロセスの名前
name: Expo App CI/CD

# このプロセスが実行されるタイミングを指定
on:
  # mainブランチにコードがプッシュされた時
  push:
    branches: [ main ]
  # mainブランチに対するプルリクエストが作成された時
  pull_request:
    branches: [ main ]

# 実行する具体的な作業内容
jobs:
  # 「test-and-build」という名前の作業
  test-and-build:
    # この作業は、Ubuntu（Linux）の最新版の上で実行します
    runs-on: ubuntu-latest

    # 作業のステップ
    steps:
      # 1. リポジトリのコードを仮想環境にコピーする
      - name: 📚 Checkout repository
        uses: actions/checkout@v4

      # 2. Node.jsの環境をセットアップする (バージョン18を指定)
      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          # npmのキャッシュを有効にして、次回のインストールを高速化
          cache: 'npm'

      # 3. ExpoとEASのツールをインストールする
      - name: 🔧 Install dependencies
        run: |
          npm install -g expo-cli eas-cli
          npm install

      # 4. コードの静的解析（リンター）を実行する
      - name: 💅 Run linter
        run: npm run lint

      # 5. テストを実行する
      - name: 🧪 Run tests
        run: npm test

      # 6. EAS BuildでAndroidアプリをビルドする
      #    (mainブランチにプッシュされた時だけ実行)
      - name: 🚀 Build with EAS
        # このif文で、mainブランチへのプッシュの時だけ実行されるように制御
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: eas build --platform android --non-interactive --profile preview
        env:
          # ★★★ このEXPO_TOKENは、次のステップで設定が必要です ★★★
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}